# Generated by Django 2.2.6 on 2019-10-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
