# Generated by Django 2.2.6 on 2019-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191010_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
