# Generated by Django 2.2.6 on 2019-10-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191010_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sum',
        ),
    ]
