# Generated by Django 2.2.6 on 2019-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_cart_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
