# Generated by Django 2.2.6 on 2019-10-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_cart_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
