# Generated by Django 2.2.6 on 2019-10-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20191010_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture_url',
        ),
    ]
