# Generated by Django 2.2.6 on 2019-10-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_goods_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_qq',
        ),
    ]
