# Generated by Django 2.2.6 on 2019-10-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20191011_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
