# Generated by Django 2.2.6 on 2019-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
