# Generated by Django 2.2.6 on 2019-10-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
