# Generated by Django 2.2.6 on 2019-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20191012_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statue',
            field=models.BooleanField(default=False),
        ),
    ]
