# Generated by Django 2.2.6 on 2019-10-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_order_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statue',
            new_name='status',
        ),
    ]
